import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Underdog, Nunito } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "../providers/ConvexClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Nunito({
  subsets: ["latin"],
  weight: "500",
});

const underdog = Underdog({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className=" ">
        <main className={roboto.className}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </main>
      </body>
    </html>
  );
}
